name=MKShared
version=1.0.0

author=Narciso Ivan Cisneros Acosta

maintainer=Narciso Ivan Cisneros Acosta

sentence=Shared library for MarioKart ESP32.

paragraph=Shared protocol, configuration and utilities.

category=Communication

architectures=esp32
includes=MKShared.h